### ISSUE TITLE
vagrant up breaks host node_modules

### ISSUE THREAD

**Issue by jasonaowen** [PermanentOrg/devenv#12]
#### Current Behavior

We share several directories between the host and guest systems, including the `mdot` and `upload-service` repos. Those are JavaScript applications, and their dependencies are installed by `npm` into `node_modules` directories.

Unfortunately, due to platform differences and the limitations of shared filesystems, symlinks do not work properly. Permanent developers are variously using Linux, macOS, and Windows.

Our previous solution to that problem is to wipe `node_modules`, recreate it locally outside of a shared folder, and then move it back into place in the shared folder. [Source](https://github.com/PermanentOrg/devenv/blob/850c7617ca446282cf885ea92e90ca9b8abd027f/bin/deploy.sh#L50-L82).

This causes issues in working with those repos in the host operating system, as the `node_modules` is now from an alien operating system. Some dependencies work differently on different OSes (notably including [fsevents](https://www.npmjs.com/package/fsevents)), the guest might have a different version of npm installed than the host, and - most importantly - we're installing with `--no-bin-links`, which means we can't have idiomatic npm scripts because `node_modules/.bin` is not populated.

#### Steps to Reproduce
Code, command line, or other relevant input.

```
cd mdot
npm install
npm run build
# this works, as node_modules/.bin/ng exists

cd ../devenv
vagrant up

cd ../mdot
npm run build
# this fails: sh: 1: ng: not found
```

#### Expected Behavior

The host environment should not be affected by provisioning a new vagrant instance.

#### Possible Solutions

Instead of building in vagrant in the shared folder, we can build outside of the shared folder, and then move the built assets into the shared folder.

Approximately:

```
cp -r /data/www/mdot ~/mdot
cd ~/mdot
npm ci
npm run build
rm -rf /data/www/mdot/dist
mv ~/mdot/dist /data/www/mdot/
```

(There's some additional nuance with the initial copy; we need to exclude the initial `node_modules`.)

I think it's okay to wipe out the build directory on the host; it's still not great for the guest to affect the host, but having the build directory shared allows us to build on the host and serve from the guest, which I think is a good tradeoff.

#### Related Issues

https://github.com/PermanentOrg/upload-service/pull/22

See also [private Slack conversation](https://permanent-org.slack.com/archives/GC4998R1R/p1605026284131500)

https://stackoverflow.com/questions/17895256/creating-symbolic-link-protocol-error

**Comment by xmunoz** [comment]
Related: https://github.com/npm/npm/issues/992

**Comment by jasonaowen** [comment]
After discussing this with @mithuna, I propose that we solve this issue by not doing any `npm` actions during `vagrant up`.

The goal of having these commands originally seems to have been to a create a complete, working instance of the Permanent application. That allows developers to get started quickly, and particularly developers who are not making any changes to any of the JavaScript repositories, but this issue prevents developers from being effective long-term. As we migrate more and more towards JavaScript (or TypeScript), this becomes a worse and worse trade-off.

Instead, let's let developers manage their own environments. This means that there are additional steps that developers need to take before they have a complete environment, but makes developing on our various JavaScript repos easier by allowing developers to build and edit in their host operating system rather than in the Vagrant machine.

We can map the build folders into the Vagrant machine, so that Apache or systemd is still able to see the final product.
