### ISSUE TITLE
Should we add share/ and log to gitignore?

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/devenv#2]
#### Description
The setup instructions involve creating two folders `share` and `log` in addition to writing to a `share/sqs.txt`

We don't want to track the contents of these folders; should we add them to gitignore?

On a related note, should we also check in a `share/.gitkeep` and `log/.gitkeep` so that creating those directories is no longer part of the setup instructions?

**Comment by xmunoz** [comment]
Hmm, maybe the instructions aren't clear. These directories need to be created one level up from the root of this (or any other) repository.

**Comment by slifty** [comment]
Well now I feel silly!  Thank you for clarifying (it worked because I did it correctly the first time 😂) -- closing now.
